### ISSUE TITLE
Phalcon PHP 7 Debian 3.0.0 no longer available

### ISSUE THREAD

**Issue by HanXHX** [phalcongelist/packagecloud#6]
Hi,

According with my last issue (#5), Phalcon 3.0.0 is no longer available for PHP 7 and Debian Jessie.

I can't use 3.0.1 (bugs). Can you "reupload" or something else? 3.0.0 version is still available for Stretch.

https://packagecloud.io/app/phalcon/stable/search?filter=all&q=php7.0-phalcon_3.0.0&dist=debian

Thanks.

HanXHX

**Comment by sergeyklay** [comment]
Done
