### ISSUE TITLE
Phalcon extension unloaded after system upgrade

### ISSUE THREAD

**Issue by rLoka** [phalcongelist/packagecloud#7]
So, I am using Phalcon 3.0.0 with PHP 7 on Ubuntu 16.04.1 on DO. Everything worked correctly until today, when I ran `apt update and upgrade` on Ubuntu. After the process finished, Phalcon plugin seems to be unloaded, since there is no phalcon entry in phpinfo(), also giving the: 

    Fatal error: Uncaught Error: Class 'Phalcon\Config' not found in /var/www/example.com/app/config/config.php

I am using https://packagecloud.io/phalcon/stable/ubuntu xenial/main for phalcon repo

Here is what got upgraded:

    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    Calculating upgrade... Done
    The following NEW packages will be installed:
      linux-headers-4.4.0-62 linux-headers-4.4.0-62-generic linux-image-4.4.0-62-generic
    The following packages will be upgraded:
      apport apt apt-utils bind9-host bsdutils cloud-init cloud-initramfs-copymods cloud-initramfs-dyn-netconf cloud-initramfs-growroot dbus dnsutils grub-common grub-pc grub-pc-bin grub2-common ifupdown
      initramfs-tools initramfs-tools-bin initramfs-tools-core isc-dhcp-client isc-dhcp-common krb5-locales libapache2-mod-php7.0 libapt-inst2.0 libapt-pkg5.0 libbind9-140 libblkid1 libc-bin libc-dev-bin libc6
      libc6-dev libdbus-1-3 libdns-export162 libdns162 libfdisk1 libglib2.0-0 libglib2.0-data libgnutls-openssl27 libgnutls30 libgssapi-krb5-2 libhogweed4 libisc-export160 libisc160 libisccc140 libisccfg140
      libk5crypto3 libkrb5-3 libkrb5support0 liblwres141 liblxc1 libmount1 libnettle6 libnss-myhostname libpam-systemd libprocps4 libsmartcols1 libssl-dev libssl-doc libssl1.0.0 libsystemd0 libudev1 libuuid1
      libxpm4 linux-headers-generic linux-headers-virtual linux-headers-virtual-lts-xenial linux-image-virtual linux-libc-dev linux-virtual linux-virtual-lts-xenial locales lxc-common lxcfs lxd lxd-client mount
      multiarch-support nano ntfs-3g open-iscsi openssl overlayroot php7.0 php7.0-cgi php7.0-cli php7.0-common php7.0-curl php7.0-dev php7.0-gd php7.0-json php7.0-ldap php7.0-mbstring php7.0-opcache php7.0-pgsql
      php7.0-phalcon php7.0-readline php7.0-soap php7.0-sqlite3 php7.0-xml php7.0-xmlrpc php7.0-zip procps python-cryptography python-software-properties python3-apport python3-cryptography python3-distupgrade
      python3-problem-report python3-software-properties python3-update-manager snap-confine snapd software-properties-common systemd systemd-sysv tzdata ubuntu-core-launcher ubuntu-release-upgrader-core udev
      unattended-upgrades update-manager-core update-notifier-common util-linux uuid-runtime vim vim-common vim-runtime vim-tiny
    128 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
    Need to get 93.3 MB of archives.
    After this operation, 155 MB of additional disk space will be used.
    Do you want to continue? [Y/n] Y

    Get: https://packagecloud.io/phalcon/stable/ubuntu xenial/main .....

Here is the full upgrade log: http://pastebin.com/FDKd9yQw

Here is full phpinfo: https://image.ibb.co/duf7rF/phpinfo.jpg

I tried removing and installing package manually but it didn't work.

**Comment by sergeyklay** [comment]
> Creating config file /etc/php/7.0/mods-available/phalcon.ini with new version

did you tried `phpenmod phalcon`?

**Comment by rLoka** [comment]
I fixed it.

Ran `phpenmod phalcon` and rebooted the server and it worked.
